import fs from 'node:fs';import path from 'node:path';import {pathToFileURL} from 'node:url';
// Repack copies only: retain fighting clips and all mesh/skin/image data, prune unreachable accessors.
export function optimize(file){const b=fs.readFileSync(file),jsonLength=b.readUInt32LE(12),j=JSON.parse(b.subarray(20,20+jsonLength));if(j.extensionsUsed?.some(e=>!e.startsWith('KHR_materials_')))throw Error('Unsupported extensions: '+file);const binary=b.subarray(28+jsonLength);j.animations=(j.animations??[]).filter(a=>a.name.startsWith('fighting_'));
 const used=new Set();const add=i=>{if(i!==undefined)used.add(i)};
 for(const m of j.meshes??[])for(const p of m.primitives){Object.values(p.attributes).forEach(add);add(p.indices);for(const t of p.targets??[])Object.values(t).forEach(add)}
 for(const s of j.skins??[])add(s.inverseBindMatrices);for(const a of j.animations)for(const s of a.samplers){add(s.input);add(s.output)}
 const accessors=[...used].sort((a,b)=>a-b),amap=new Map(accessors.map((a,i)=>[a,i]));
 for(const m of j.meshes??[])for(const p of m.primitives){for(const k in p.attributes)p.attributes[k]=amap.get(p.attributes[k]);if(p.indices!==undefined)p.indices=amap.get(p.indices);for(const t of p.targets??[])for(const k in t)t[k]=amap.get(t[k])}
 for(const s of j.skins??[])if(s.inverseBindMatrices!==undefined)s.inverseBindMatrices=amap.get(s.inverseBindMatrices);for(const a of j.animations)for(const s of a.samplers){s.input=amap.get(s.input);s.output=amap.get(s.output)}j.accessors=accessors.map(i=>j.accessors[i]);
 const views=new Set();for(const a of j.accessors){if(a.bufferView!==undefined)views.add(a.bufferView);if(a.sparse){views.add(a.sparse.indices.bufferView);views.add(a.sparse.values.bufferView)}}for(const image of j.images??[])if(image.bufferView!==undefined)views.add(image.bufferView);
 const indices=[...views].sort((a,b)=>a-b),vmap=new Map(indices.map((a,i)=>[a,i]));let offset=0;const chunks=[];const nextViews=[];for(const i of indices){const v=j.bufferViews[i];if(v.buffer!==0)throw Error('External buffer unsupported');const chunk=binary.subarray(v.byteOffset??0,(v.byteOffset??0)+v.byteLength);chunks.push(chunk);nextViews.push({...v,byteOffset:offset});offset+=chunk.length;const pad=(4-offset%4)%4;if(pad){chunks.push(Buffer.alloc(pad));offset+=pad}}
 for(const a of j.accessors){if(a.bufferView!==undefined)a.bufferView=vmap.get(a.bufferView);if(a.sparse){a.sparse.indices.bufferView=vmap.get(a.sparse.indices.bufferView);a.sparse.values.bufferView=vmap.get(a.sparse.values.bufferView)}}for(const image of j.images??[])if(image.bufferView!==undefined)image.bufferView=vmap.get(image.bufferView);j.bufferViews=nextViews;j.buffers=[{byteLength:offset}];
 let text=JSON.stringify(j);text+=' '.repeat((4-Buffer.byteLength(text)%4)%4);const jb=Buffer.from(text),bin=Buffer.concat(chunks),head=Buffer.alloc(20),bh=Buffer.alloc(8);head.writeUInt32LE(0x46546c67);head.writeUInt32LE(2,4);head.writeUInt32LE(28+jb.length+bin.length,8);head.writeUInt32LE(jb.length,12);head.writeUInt32LE(0x4e4f534a,16);bh.writeUInt32LE(bin.length);bh.writeUInt32LE(0x004e4942,4);fs.writeFileSync(file,Buffer.concat([head,jb,bh,bin]));return [b.length,28+jb.length+bin.length];}
const walk=d=>fs.readdirSync(d,{withFileTypes:true}).flatMap(e=>e.isDirectory()?walk(path.join(d,e.name)):[path.join(d,e.name)]);
if(process.argv[1]&&import.meta.url===pathToFileURL(process.argv[1]).href){let before=0,after=0;for(const f of walk('public/fighters').filter(f=>f.endsWith('.glb')&&!f.includes('physics'))){const sizes=optimize(f);before+=sizes[0];after+=sizes[1]}console.log(`GLB runtime: ${(before/1e6).toFixed(1)} → ${(after/1e6).toFixed(1)} MB. Original exports untouched.`);}
